create schema cars
SELECT * FROM car_dekho
USE CARS
#### READ DATA
SELECT * FROM car_dekho
####  TOTAL CARS: TO GET A COUNT OF TOTAL RECORDS
SELECT COUNT(*) FROM CAR_DEKHO
#### NO OF CARS THAT WILL BE AVAILABLE IN 2023
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR = 2023
#### NO OF CARS THAT WILL BE AVAILABLE IN 2020,2021,2022
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR IN(2020,2021,2022)
#### NO OF CARS THAT WILL BE AVAILABLE IN 2020,2021,2022 USING GROUP BY
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR IN(2020,2021,2022) GROUP BY YEAR
#### PRINT THE TOTAL AVAILABLE  ALL CARS YEAR WISE
SELECT YEAR, COUNT(*) FROM CAR_DEKHO GROUP BY YEAR
#### HOW MANY DIESEL CARS WILL BE AVAILABLE IN 2020
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR  = 2020  AND FUEL ="Diesel"
#### HOW MANY PETROL CARS WILL BE AVAILABLE IN 2020
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR  = 2020  AND FUEL ="PETROL"
#### ALL THE FUEL CARS ( PETROL.DIESEL,CNG) AVAILABLE ALL YEARS
SELECT YEAR, FUEL,  COUNT(*) FROM CAR_DEKHO WHERE  FUEL = "PETROL" GROUP BY YEAR, FUEL
SELECT YEAR, FUEL,  COUNT(*) FROM CAR_DEKHO WHERE  FUEL = "DIESEL" GROUP BY YEAR, FUEL
SELECT YEAR, FUEL,  COUNT(*) FROM CAR_DEKHO WHERE  FUEL = "CNG" GROUP BY YEAR, FUEL
#### THERE WERE MORE THAN 100 CARS IN GIVEN YEAR, IN  PARTICULARALY  WHICH YEAR HAD MORE THAN 100 CARS
SELECT YEAR, FUEL, COUNT(*) FROM CAR_DEKHO GROUP BY YEAR,FUEL HAVING COUNT(*)>100
SELECT YEAR, FUEL, COUNT(*) FROM CAR_DEKHO GROUP BY YEAR,FUEL HAVING COUNT(*)<100
#### ALL CARS DETAILS BETWEEN 2015 - 2023 COMPLETE LIST
SELECT * FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023
#### COUNT OF ALL CARS DETAILS BETWEEN 2015 - 2023 COMPLETE LIST
SELECT COUNT(*) FROM CAR_DEKHO WHERE YEAR BETWEEN 2015 AND 2023














